Repository vesoft-inc/nebula-docs-cn, pull requests merged in 2023-05, with the labels that each got.

#2739 [LICENSE] LICENSE SUITE
  docs-2.0/9.about-license/2.license-management-suite/1.suite-overview.md
Labels: wip

#2737 [LICENSE]LC
  docs-2.0/9.about-license/2.license-management-suite/2.license-center.md
Labels: wip

#2735 [LICENSE]PURCHASE
  docs-2.0/9.about-license/3.purchase-license.md
Labels: wip

#2734 [LICENSE]LOAD KEY
  docs-2.0/9.about-license/4.generate-and-load-license-key.md
Labels: wip

#2733 [LICENSE]MANAGE-LICENSE
  docs-2.0/9.about-license/5.manage-license.md
Labels: wip

#2784 Update 6.cheatsheet-for-ngql-command.md
  docs-2.0/2.quick-start/6.cheatsheet-for-ngql-command.md
Labels: already-auto-picked-master

#2789 increment-changes-on-ent-docs
  docs-2.0/20.appendix/0.FAQ.md
  docs-2.0/20.appendix/error-code.md
  docs-2.0/20.appendix/learning-path.md
  docs-2.0/4.deployment-and-installation/1.resource-preparations.md
  docs-2.0/4.deployment-and-installation/2.compile-and-install-nebula-graph/4.install-nebula-graph-from-tar.md
  docs-2.0/4.deployment-and-installation/2.compile-and-install-nebula-graph/deploy-nebula-graph-cluster.md
  docs-2.0/nebula-importer/use-importer.md
  docs-2.0/reuse/source_connect-to-nebula-graph.md
  docs-2.0/reuse/source_install-nebula-graph-by-rpm-or-deb.md
  docs-2.0/reuse/source_manage-service.md
  mkdocs.yml
Labels: cherry-pick-to-v3.5.0

#2781 allow-expression-like-return-v.tag
  docs-2.0/3.ngql-guide/8.clauses-and-options/return.md
Labels: already-auto-picked-v3.5.0

#2805 Delete the trial content of visual products in the enterprise version
  docs-2.0/graph-computing/use-explorer.md
  docs-2.0/nebula-dashboard-ent/1.what-is-dashboard-ent.md
  docs-2.0/nebula-dashboard-ent/2.deploy-connect-dashboard-ent.md
  docs-2.0/nebula-dashboard-ent/8.faq.md
  docs-2.0/nebula-dashboard-ent/system-settings/manage-package.md
  docs-2.0/nebula-explorer/about-explorer/ex-ug-what-is-explorer.md
  docs-2.0/nebula-explorer/deploy-connect/ex-ug-deploy.md
Labels: cherry-pick-to-v3.5.0
